<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Language_MarketplaceLogo__Logo-sc-1so4i_8095ee</name>
   <tag></tag>
   <elementGuidId>688f679d-0b58-4cfd-89d9-654edc23ff23</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img.MarketplaceLogo__Logo-sc-1so4i7o-0.ixapQh</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/section/header/div/a/div/div/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>79bb0a12-c504-4402-a7f0-369639beb6cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://assets.99smeb2b.com/development/company/6497b9b4-cec9-4ffa-bf74-ea56f65e17f3</value>
      <webElementGuid>509ec635-ff20-4810-9538-8a3afe70ddf5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>logo</value>
      <webElementGuid>a398a952-c572-4b9d-8a98-b25c733d969b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MarketplaceLogo__Logo-sc-1so4i7o-0 ixapQh</value>
      <webElementGuid>24896251-80cb-4081-983e-a4ef90439e45</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/section[@class=&quot;ManagerPage__StyledLayout-sc-1vh9jsi-4 epsKbp ant-layout&quot;]/header[@class=&quot;ant-layout-header&quot;]/div[1]/a[1]/div[@class=&quot;ManagerPage__LogoWrapper-sc-1vh9jsi-0 hNqiHc&quot;]/div[1]/img[@class=&quot;MarketplaceLogo__Logo-sc-1so4i7o-0 ixapQh&quot;]</value>
      <webElementGuid>e1c99e51-4060-48df-b844-cfc17a9f3abd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/section/header/div/a/div/div/img</value>
      <webElementGuid>6d496837-c180-4404-92da-0dd2599ff476</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='logo']</value>
      <webElementGuid>3d884598-8310-43e1-85bf-b5cea222b534</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//img</value>
      <webElementGuid>8c33928b-548c-4630-82d0-0fdb570d71c9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://assets.99smeb2b.com/development/company/6497b9b4-cec9-4ffa-bf74-ea56f65e17f3' and @alt = 'logo']</value>
      <webElementGuid>b61a96ce-547b-4316-b1e8-e25d788b959d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
