<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Remove</name>
   <tag></tag>
   <elementGuidId>9438dafc-44ab-47cd-b1d3-71e29e0bc9a0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.del-item</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='body-wrapper']/div/div/div/div[3]/div/div[4]/div[2]/div/div[2]/p/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>46351814-eca0-4124-9534-73cd811c7425</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>del-item</value>
      <webElementGuid>958336d9-270f-41b0-acd3-e6df437f349e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Remove</value>
      <webElementGuid>02ba1879-8ccd-48de-b75d-0cfd9f53a20a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;body-wrapper&quot;)/div[@class=&quot;container&quot;]/div[@class=&quot;CartPage__CartPageWrapper-sc-1dkogce-0 hFUHYZ&quot;]/div[@class=&quot;CartPage__CartPageContentWrapper-sc-1dkogce-3 bWyEeX&quot;]/div[@class=&quot;ant-row CartPage__TableItem-sc-1dkogce-5 oFLSb&quot;]/div[@class=&quot;ant-row ItemListPerStore__StyledItemWrapper-crjgbw-1 eYGEFB&quot;]/div[@class=&quot;ant-row ItemListPerStore__CartItemRow-crjgbw-2 epBLIs&quot;]/div[@class=&quot;ant-col ant-col-xs-22 ant-col-md-8&quot;]/div[@class=&quot;item-info&quot;]/div[@class=&quot;names&quot;]/p[@class=&quot;action-item&quot;]/span[@class=&quot;del-item&quot;]</value>
      <webElementGuid>a6555e70-4d71-4e50-903b-27a2674a544c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='body-wrapper']/div/div/div/div[3]/div/div[4]/div[2]/div/div[2]/p/span</value>
      <webElementGuid>c3a56ae4-b919-45ec-a6cd-7f2e194fb549</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Unit Price'])[1]/following::span[4]</value>
      <webElementGuid>a0edcac4-4327-4225-af28-aa8932bdda7c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Attachment'])[1]/preceding::span[1]</value>
      <webElementGuid>88935c3e-1622-4f19-b40f-67052bb4c069</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select spend category'])[1]/preceding::span[3]</value>
      <webElementGuid>49c3c74c-0c5b-4ea4-bce6-df608293dcac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Remove']/parent::*</value>
      <webElementGuid>68323a7b-d4a5-458e-9190-18e9a4960eef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p/span</value>
      <webElementGuid>44baacb0-4b33-42cb-b572-0ecdd4dc8a77</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Remove' or . = 'Remove')]</value>
      <webElementGuid>40a6539b-3cf9-4419-807e-be1f6036ff48</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
