<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_ProCase Pencil Bag Pen Case, Big Capaci_eea970</name>
   <tag></tag>
   <elementGuidId>70b571c5-d3e3-48df-8a40-9054fad1d925</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.ant-row.ItemListPerStore__CartItemRow-crjgbw-2.epBLIs</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='body-wrapper']/div/div/div/div[3]/div/div[4]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>53a0fbb7-6190-4214-a1fb-2962767cd0d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ant-row ItemListPerStore__CartItemRow-crjgbw-2 epBLIs</value>
      <webElementGuid>121f316f-1dcf-4eef-b87b-1804c784ee4a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>ProCase Pencil Bag Pen Case, Big Capacity Students Stationery Pouch Holder Desk Organizer with Zipper for Pens Pencils Highlighters Gel Pen Markers School Supplies Students Office Clerks -BlackRemoveAttachmentSelect spend categorytestspend Add NoteSGD 16.55SGD 16.55</value>
      <webElementGuid>ac322b66-8ccc-42cd-a852-64f1ecd15420</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;body-wrapper&quot;)/div[@class=&quot;container&quot;]/div[@class=&quot;CartPage__CartPageWrapper-sc-1dkogce-0 hFUHYZ&quot;]/div[@class=&quot;CartPage__CartPageContentWrapper-sc-1dkogce-3 bWyEeX&quot;]/div[@class=&quot;ant-row CartPage__TableItem-sc-1dkogce-5 oFLSb&quot;]/div[@class=&quot;ant-row ItemListPerStore__StyledItemWrapper-crjgbw-1 eYGEFB&quot;]/div[@class=&quot;ant-row ItemListPerStore__CartItemRow-crjgbw-2 epBLIs&quot;]</value>
      <webElementGuid>e96bb6e0-e7e9-4bd1-b805-80ca85ff1c50</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='body-wrapper']/div/div/div/div[3]/div/div[4]</value>
      <webElementGuid>5f651f4d-3c64-453e-ae8d-b0ba5a9dd1f7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Unit Price'])[1]/following::div[2]</value>
      <webElementGuid>ad94f410-edb1-4d39-8110-012a73494061</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div[4]</value>
      <webElementGuid>1c3fcce0-bfaa-4ac6-8697-8965f0b36406</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'ProCase Pencil Bag Pen Case, Big Capacity Students Stationery Pouch Holder Desk Organizer with Zipper for Pens Pencils Highlighters Gel Pen Markers School Supplies Students Office Clerks -BlackRemoveAttachmentSelect spend categorytestspend Add NoteSGD 16.55SGD 16.55' or . = 'ProCase Pencil Bag Pen Case, Big Capacity Students Stationery Pouch Holder Desk Organizer with Zipper for Pens Pencils Highlighters Gel Pen Markers School Supplies Students Office Clerks -BlackRemoveAttachmentSelect spend categorytestspend Add NoteSGD 16.55SGD 16.55')]</value>
      <webElementGuid>e3b00768-9c91-4696-8738-dca146dcf120</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
