<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Add Note_ant-input-number-input</name>
   <tag></tag>
   <elementGuidId>a3eaf0e5-e067-45c8-8462-092c9007569d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[2]/input</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input.ant-input-number-input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>66c7e9d6-3d22-457d-b81a-9ee234b86782</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>spinbutton</value>
      <webElementGuid>33954b61-269f-480f-a7e6-97fa82b907ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-valuemin</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>30a434a6-640d-4171-b43d-0939472e11d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-valuenow</name>
      <type>Main</type>
      <value>9</value>
      <webElementGuid>bddf6f8e-2b47-46d8-a008-f5dffb55e9e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ant-input-number-input</value>
      <webElementGuid>932ca370-9d8a-44ae-a13b-0f5f940e15af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>beb6a7b4-6f64-4fb7-b279-0d527627426c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>min</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>bb13c4ac-84a8-4e2c-b865-cd1986ef1977</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>step</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>0e2ad3c3-ca08-4636-877d-3df6eac1ef64</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>9</value>
      <webElementGuid>705ef41c-1ee4-4578-9519-4e333ebfd8d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;body-wrapper&quot;)/div[@class=&quot;container&quot;]/div[@class=&quot;CartPage__CartPageWrapper-sc-1dkogce-0 hFUHYZ&quot;]/div[@class=&quot;CartPage__CartPageContentWrapper-sc-1dkogce-3 bWyEeX&quot;]/div[@class=&quot;ant-row CartPage__TableItem-sc-1dkogce-5 oFLSb&quot;]/div[@class=&quot;ant-row ItemListPerStore__StyledItemWrapper-crjgbw-1 eYGEFB&quot;]/div[@class=&quot;ant-row ItemListPerStore__CartItemRow-crjgbw-2 epBLIs&quot;]/div[@class=&quot;ant-col ItemListPerStore__StyledCol-crjgbw-0 duVuia two-column-mobile-layout ant-col-xs-22 ant-col-xs-offset-2 ant-col-md-3 ant-col-md-offset-0&quot;]/div[@class=&quot;ant-input-number ant-input-number-focused&quot;]/div[@class=&quot;ant-input-number-input-wrap&quot;]/input[@class=&quot;ant-input-number-input&quot;]</value>
      <webElementGuid>28836993-f6b1-4b87-ab6d-5790b1b9dd5c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@value='9']</value>
      <webElementGuid>6f17a271-700f-4030-8ff3-ffe374632aac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='body-wrapper']/div/div/div/div[3]/div/div[4]/div[4]/div/div[2]/input</value>
      <webElementGuid>76fb9c92-4c35-44f4-b3ae-bb959c00d1cb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input</value>
      <webElementGuid>1189dada-9e17-4f97-a422-59b96120e83e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
